void Dir(AsyncWebServerRequest *);
void Directory(void);
void UploadFileSelect(void);
void Format(void);
void handleFileUpload(AsyncWebServerRequest *, const String *, size_t, uint8_t *, size_t, bool);
void File_Stream(void);
void File_Delete(void);
void Handle_File_Delete(String filename);
void File_Rename(void);
void Handle_File_Rename(AsyncWebServerRequest *, String, int);
void notFound(AsyncWebServerRequest *);
void Handle_File_Download(void);
String getContentType(String);
void Select_File_For_Function(String, String);
void SelectInput(String, String, String);
int GetFileSize(String);
void Home(void);
void Page_Not_Found(void);
void Display_About(void);
String ConvBinUnits(int, int);
String EncryptionType(wifi_auth_mode_t);
bool StartMDNSservice(const char*);
String HTML_Header(void);
String HTML_Footer(void);